# Generated by Django 3.0 on 2019-12-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='0000000', max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='headline',
            field=models.CharField(default='0000000', max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='download.jpg', upload_to='images/'),
        ),
    ]
